In [4]:
import numpy as np
a= np.array([[10],[11],[12]])
print(a)

[[10]
 [11]
 [12]]


In [5]:
print(type(a))

<class 'numpy.ndarray'>


In [7]:
print(a.shape) #returns tuple ( the shape of the array ), returns the no. of element in each dimension

(3, 1)


In [8]:
print(a.ndim) #returns dimension of array

2


In [9]:
an= np.array([[[10],[11],[12]]])
print(an)

[[[10]
  [11]
  [12]]]


In [10]:
print(an.shape)
print(an.ndim)

(1, 3, 1)
3


In [14]:
VD = np.array([15,4,11,31])
print(VD)
RD = VD.reshape(2,2) #reshapes the array into another without changing its data
print(RD)

[15  4 11 31]
[[15  4]
 [11 31]]


In [18]:
v=np.arange(12)
print(v)


[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [47]:
print(v.ndim)

1


In [28]:
v=np.arange(12)
print(v)

b= v.reshape(4,3)   #we can reshape array only if the elements required are equal , as it will give error when elements are not equally distributed
print(b)
print(b.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2


In [25]:
V=np.ones((3,3))    #It creates an array having all ones of shape 3,3
print(V)
print(V.ndim)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
2


In [8]:
D=np.zeros((3,3))   #It creates an array having all zeros of shape 3,3
print(D)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
ve = np.random.random((3,3))   #It creates array of random values
print(ve)

[[0.30549126 0.80131215 0.90491048]
 [0.70955123 0.42579493 0.69615541]
 [0.19359084 0.79329087 0.09858226]]


In [12]:
rd=np.full((4,3),15)
print(rd)

[[15 15 15]
 [15 15 15]
 [15 15 15]
 [15 15 15]]


In [31]:
S=np.array([9,8,7,6,5,4])
print(S)
print(S.dtype)
S=np.array([9,8,7,6,5,4],dtype=np.float32)   #You can explicitly specify which data-type you want 
print(S)
print(S.dtype)

[9 8 7 6 5 4]
int32
[9. 8. 7. 6. 5. 4.]
float32


In [32]:
a = np.ones((3, 3))
a.dtype

dtype('float64')

In [34]:
a=np.eye(5)  #Return a 2-D array with ones on the diagonal and zeros elsewhere.
print(a) 
a.dtype

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


dtype('float64')