In [1]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv('spam ham.csv',encoding=('ISO-8859-1'))
df.head()

category                                           messages
0      ham  India, also known as Bharat, is a Union of Sta...
1     spam  India, also known as Bharat, is a Union of Sta...
2      ham  India, also known as Bharat, is a Union of Sta...
3      ham  India, also known as Bharat, is a Union of Sta...
4     spam  India, also known as Bharat, is a Union of Sta...

In [5]:
df.groupby('category').describe()

messages                                                            \
            count unique                                                top   
category                                                                      
ham            15      4  The Constitution of India (IAST: Bh?rat?ya Sa?...   
spam           15      4  India, also known as Bharat, is a Union of Sta...   

               
         freq  
category       
ham         6  
spam        8

In [6]:
df['spam']=df['category'].apply(lambda x: 1 if x=='spam' else 0)
df.head()

category                                           messages  spam
0      ham  India, also known as Bharat, is a Union of Sta...     0
1     spam  India, also known as Bharat, is a Union of Sta...     1
2      ham  India, also known as Bharat, is a Union of Sta...     0
3      ham  India, also known as Bharat, is a Union of Sta...     0
4     spam  India, also known as Bharat, is a Union of Sta...     1

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x_train,x_test,y_train,y_test=train_test_split(df.messages,df.spam,test_size=0.25)

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()
x_train_count=v.fit_transform(x_train.values)
x_train_count.toarray()[:3]

array([[0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 1, 2, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1,
        0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
        0, 1, 0, 0, 0, 1, 2, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 2, 0,
        0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 4, 0, 0, 1, 0,
        0, 1],
       [0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 1, 2, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1,
        0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        1, 0]], dtype=int64)

In [14]:
from sklearn.naive_bayes import MultinomialNB

In [15]:
model=MultinomialNB()

In [16]:
model.fit(x_train_count,y_train)

MultinomialNB()

In [35]:
emails=[
    'my name is hp i am a computer which works like multitasking',
    'indian constitution made in nintyfifty India, also known as Bharat, is a Union of '
]
email_count=v.transform(emails)
model.predict(email_count)

array([0, 1], dtype=int64)

In [22]:
x_test_count=v.transform(x_test)
model.score(x_test_count,y_test)

0.625

In [27]:
from sklearn.pipeline import Pipeline
clf=Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [28]:
clf.fit(x_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [29]:
clf.score(x_test,y_test)

0.625

In [36]:
clf.predict(emails)

array([0, 1], dtype=int64)