# Numpy

In [1]:
import numpy as np

In [2]:
myarr=np.array([[3,6,37,7]],np.int64)

In [3]:
myarr[0]

array([ 3,  6, 37,  7], dtype=int64)

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.dtype

dtype('int64')

In [6]:
myarr[0,1]

6

In [7]:
myarr[0,1]=45

In [8]:
myarr

array([[ 3, 45, 37,  7]], dtype=int64)

# Array creation:Conversion from other python structures

In [9]:
 listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])

In [10]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [11]:
listarray.shape

(3, 3)

In [12]:
listarray.dtype

dtype('int32')

In [13]:
listarray.size

9

In [14]:
np.array({1,2,3})

array({1, 2, 3}, dtype=object)

In [15]:
zeros=np.zeros((2,5))

In [16]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
zeros.shape

(2, 5)

In [18]:
rng=np.arange(15)

In [19]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
lspace=np.linspace(1,5,12)

In [21]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [22]:
lspace2=np.linspace(1,50,10)
lspace2

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [23]:
lspace3=np.linspace(1,4,4)
lspace3

array([1., 2., 3., 4.])

In [24]:
ide=np.identity(45)

In [25]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [26]:
ide.shape

(45, 45)

In [27]:
emp=np.empty((4,6))

In [28]:
emp

array([[-1.18182126e-125,  5.66141846e-314,  3.59215701e+289,
         5.82558523e-313,  5.72778078e+250,  2.32210854e-322],
       [ 2.03389368e-308,  0.00000000e+000,  0.00000000e+000,
        -1.42873512e-101,  0.00000000e+000,  2.31959604e-309],
       [-1.18182126e-125,  3.53942267e-314,  3.25938553e-310,
         3.83534280e+289, -1.28822975e-231,  1.61068576e+270],
       [ 2.07306088e-315,  6.06693669e+279,  1.24593603e-019,
         4.01711815e+289,  2.07759903e-315,  4.50340097e+289]])

In [29]:
empl=np.empty_like(lspace3)
empl

array([1., 2., 3., 4.])

In [30]:
arr=np.arange(99)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [32]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [34]:
arr=arr.reshape(3,33)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [35]:
arr=arr.ravel()

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [37]:
arr.shape 

(99,)

In [38]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [39]:
ar=np.array(x)

In [40]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [41]:
ar.sum(axis=0)

array([12,  8,  9])

In [42]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [43]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [44]:
ar.flat

In [45]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [46]:
ar.ndim

2

In [47]:
ar.size

9

In [48]:
ar.nbytes

36

In [49]:
one=np.array([1,3,4,634,2])

In [50]:
one.argmax()

3

In [51]:
one.argmin()

0

In [52]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [53]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [54]:
ar.argmin()

8

In [55]:
ar.argmax()

6

In [56]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [57]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [58]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [59]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [60]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [61]:
ar2=np.array([[1,2,1],[4,0,6],[8,1,0]])

In [62]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [63]:
[1,2]+[3,4]

[1, 2, 3, 4]

In [64]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [65]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [66]:
ar.sum()

29

In [67]:
ar.max()

7

In [68]:
ar.min()

0

In [70]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [71]:
type(np.where(ar>5))

tuple

In [72]:
np.count_nonzero(ar)

8

In [75]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [76]:
ar[1,2]=0

In [77]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [78]:
import sys

In [82]:
py_ar=[0,4,55,2]

In [83]:
np_ar=np.array(py_ar)

In [84]:
sys.getsizeof(1)*len(py_ar)

112

In [85]:
np_ar.itemsize*np_ar.size

16

In [86]:
np_ar.tolist()

[0, 4, 55, 2]