# Numpy array 


1. it is a grid of values, all of same type and is  indexed by a tuple of positive integers
2. array class in numpy is called ndarray
3. elements in numpy array can be accesssed by using square bracket and can be intialized by  using python list

In [6]:
import numpy as np
a=np.array([[10],[50],[30]])
print(type(a))


<class 'numpy.ndarray'>


In [3]:
print(a.shape)

(3, 1)


In [4]:
print(a.ndim)

2


In [5]:
print(a)

[[10]
 [50]
 [30]]


In [11]:
AB=np.array([1,2,6,8,9,10])
print(AB)
DC=AB.reshape(2,3) # reshape
print(DC)

[ 1  2  6  8  9 10]
[[ 1  2  6]
 [ 8  9 10]]


In [15]:
a=np.arange(22)
print(a)
print(a.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]
1


In [14]:
b=a.reshape(2,4,3)
print(b)
print(b.ndim)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
3


In [11]:
A=np.ones((2,2)) #create an array of all ones
print(A)

[[1. 1.]
 [1. 1.]]


In [13]:
B=np.zeros((2,2)) #create an array of all zeroes
print(B)

[[0. 0.]
 [0. 0.]]


In [14]:
e=np.random.random((2,2))
print(e)  #create an array with random values

[[0.76246267 0.73201703]
 [0.82708532 0.50483123]]


In [9]:
D=np.full((3,2), 7) 
print(D)  #create an constant array  

[[7 7]
 [7 7]
 [7 7]]


In [21]:
P=np.array([1,2,3,4,5], dtype=np.float32)
print(P)

[1. 2. 3. 4. 5.]


In [22]:
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
